package com.example.android;

import android.app.Activity;
import android.os.AsyncTask;
import android.os.Bundle;
import com.jjoe64.graphview.GraphView;
import com.jjoe64.graphview.GraphViewSeries;
import com.jjoe64.graphview.LineGraphView;
import lecho.lib.hellocharts.model.*;
import lecho.lib.hellocharts.renderer.AxesRenderer;
import lecho.lib.hellocharts.renderer.LineChartRenderer;
import lecho.lib.hellocharts.util.AxisAutoValues;
import lecho.lib.hellocharts.view.LineChartView;

import java.security.cert.PolicyNode;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;

public  class Graph extends Activity {

    private int mNewMax;
    private Timer mTimer;
    private GraphViewSeries mExampleSeries;
    private LineGraphView graphView;
    private AsyncTask<Object, Double, Object> mTask;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Axis axisX = new Axis();
        axisX.isAutoGenerated();

        LineChartView lechoChart = new LineChartView(this);
        LineChartData lineChartData = new LineChartData();
        List<Line> lines = new ArrayList<Line>();
        List<PointValue> points = new ArrayList<PointValue>();
        points.add(new PointValue(1, 1.5f));
        points.add(new PointValue(2, 2f));
        points.add(new PointValue(3, 2.5f));
        points.add(new PointValue(4, 3f));
        points.add(new PointValue(5, 1f));
        Line line = new Line();
        line.setValues(points);

        lines.add(line);
        lineChartData.setLines(lines);
        lechoChart.setLineChartData(lineChartData);

        setContentView(lechoChart);
/*

        mExampleSeries = new GraphViewSeries(new GraphView.GraphViewData[] {
                new GraphView.GraphViewData(1, 2.0d)
                , new GraphView.GraphViewData(2, 1.5d)
                , new GraphView.GraphViewData(3, 2.5d)
                , new GraphView.GraphViewData(4, 1.0d)
        });

        mNewMax = 4;

        mTimer = new Timer();

        graphView = new LineGraphView(
                this // context
                , "GraphViewDemo" // heading
        );

        graphView.addSeries(mExampleSeries); // data

        graphView.setScrollable(true);
        setContentView(graphView);
        graphView.setScalable(true);
        graphView.setDisableTouch(true);

        graphView.setMeasureWithLargestChildEnabled(true);

        graphView.setManualYAxisBounds(100, 0); */
        mTask = new AsyncTask<Object, Double, Object> () {
            @Override
            protected Object doInBackground(Object[] params) {
                try {
                    while(true) {
                        Thread.sleep(1000);
                        publishProgress(Double.valueOf(mNewMax++));
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                return null;
            }

           /* @Override
            protected void onProgressUpdate(Double[] currentMax){
                mExampleSeries.appendData(
                        new GraphView.GraphViewData(currentMax[0], currentMax[0]),
                        true,
                        currentMax[0].intValue()
                );
                graphView.redrawAll();
            }*/
        };

        mTask.execute();
    }

}



